name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: ./front-end/tutorial-canciones
      - name: Run linters
        run: npm run lint && npm run prettier && npm run lint:html
        working-directory: ./front-end/tutorial-canciones
      - name: Run tests
        run: npm run test
        working-directory: ./front-end/tutorial-canciones
